### ISSUE TITLE
Logo pixelated

### ISSUE THREAD

**Issue by ericlbarnes** [laravelnews/site-bugs#2]
I had reports that the logo is pixelated on retina. Maybe convert to svg and/or double check sizing.

**Comment by themsaid** [comment]
<img width="265" alt="screen shot 2016-08-07 at 12 43 58 pm" src="https://cloud.githubusercontent.com/assets/4332182/17461950/75d25f0e-5c9c-11e6-82ac-fcb0426de965.png">

Yes it's a bit blurry. Maybe it's a sizing issue.

**Comment by egeriis** [comment]
It's a PNG—which of course is a bitmap—so it doesn't scale nicely on high DPI screens. Since it's 90×90px and displayed in 90×90px, it doesn't provide the double amount of pixels usually available on high DPI screens. Remember that some iPhones, and maybe other devices, have even more points per pixel.

Another issue with your logo is that is actually not 90×90px, rather it's 89×91px, so it will get distorted a bit on any screen :) 
See natural size:
![image](https://cloud.githubusercontent.com/assets/579824/17463489/e72f8c24-5cc6-11e6-8cde-dedbf67fd98f.png)

**Comment by ericlbarnes** [comment]
Fixed!
